job-service:
  url: http://job
company-service:
  url: http://company
review-service:
  url: http://review

server:
  port: 8082

spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://job-postgres:5432/job
    username: balaji
    password: balaji

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    debug: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      companyBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
        max-attempts: 5
        wait-duration: 2s
        timeout-duration: 0
        limit-refresh-period: 4
        limit-for-period: 2

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
