server:
  port: 8084 # Gateway server port

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: job-service
          uri: http://job:8082
          predicates:
            - Path=/jobs/**
        - id: company-service
          uri: http://company:8081
          predicates:
            - Path=/companies/**
        - id: review-service
          uri: http://review:8083
          predicates:
            - Path=/reviews/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans