apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  labels:
    app: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: balajiganesan1220/job:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://job-postgres:5432/job
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JOB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JOB_PASSWORD
          ports:
            - containerPort: 8082
