apiVersion: v1
kind: Service
metadata:
  name: job-postgres
  labels:
    app: job-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: job-postgres
  type: ClusterIP
