apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
  labels:
    app: company-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
    spec:
      containers:
        - name: company-service
          image: balajiganesan1220/company:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://company-postgres:5432/company
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: COMPANY_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: COMPANY_PASSWORD
          ports:
            - containerPort: 8081
