apiVersion: v1
kind: Service
metadata:
  name: company-postgres
  labels:
    app: company-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: company-postgres
  type: ClusterIP
