job-service:
  url: http://job
company-service:
  url: http://company
review-service:
  url: http://review

server:
  port: 8081

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://company-postgres:5432/company
    username: balaji
    password: balaji

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    debug: DEBUG


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
