spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/balajiganesan1220/application-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
